language: android
android:
    components:
    - tools
    - platform-tools
    - build-tools-28
    - android-28

jdk:
  - oraclejdk8

before_install:
  - sdkmanager tools

install: ./gradlew clean build assembleAndroidTest --stacktrace

notifications:
  email: true

sudo: false

cache:
  directories:
    - $HOME/.gradle