package com.sirionrazzer.diary.boarding

enum class AuthError {
    ERROR_INVALID_USER,
    ERROR_INVALID_CREDENTIALS,
    ERROR_CREDENTIAL_ALREADY_IN_USE,
    ERROR_FIREBASE_ERROR,
    ERROR_WEAK_PASSWORD,
    ERROR_NETWORK_ERROR,
    ERROR_RECENT_LOGIN_REQUIRED,
    NONE
}